name: Deploy Docs
on:
  push:
    branches:
      - main
  workflow_dispatch: # 支持网页手动触发构建

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # 去掉 --frozen-lockfile，先兼容无锁文件场景
      - name: Install Dependencies
        run: pnpm install

      - name: Build Docs
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |
          pnpm run docs:build
          # 生成 .nojekyll 防止 GitHub Pages 忽略下划线文件夹
          touch docs/.vuepress/dist/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # 必须改成 gh-pages，不能写 main！！
          folder: docs/.vuepress/dist
          clean: true